services:
  - type: web
    name: telegram-vedio-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7823731827:AAFoCU1etlCutbNiASDOCQMtHRE2qJW9eKE
